# Generated by Django 3.1.3 on 2020-11-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20201109_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_on',
        ),
    ]
