# Generated by Django 3.1.3 on 2020-11-30 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_query_title'),
        ('comments', '0004_remove_comment_commented_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='query.query'),
            preserve_default=False,
        ),
    ]
