# Generated by Django 3.1.3 on 2020-11-30 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import query.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2500)),
                ('image', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image2', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image3', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image4', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image5', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image6', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image7', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image8', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image9', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('image10', models.FileField(blank=True, null=True, upload_to=query.models.upload_loaction, validators=[query.models.file_size])),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('commented_by', models.ManyToManyField(related_name='commented_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
