# Generated by Django 3.1.3 on 2020-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_query_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
