# Generated by Django 3.1.3 on 2020-12-01 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20201130_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='heading',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
