# Generated by Django 3.1.3 on 2020-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_on',
            field=models.ManyToManyField(related_name='commented_on', to='query.Query'),
        ),
    ]
