# Generated by Django 3.1.3 on 2020-11-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_query_title'),
        ('userprofile', '0004_remove_userprofile_comment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_on',
            field=models.ManyToManyField(related_name='commented_on', to='query.Query'),
        ),
    ]
